version: "3"

services:
  nowcasting_data_visualization:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TESTING: 1
    environment:
      - API_URL=$API_URL
    command: >
      bash -c "pytest --cov=./application
      && coverage report -m
      && coverage xml
      && cp .coverage ./tests/
      && cp coverage.xml ./tests/"
    volumes:
      - ./application/:/app/application
      - ./tests/:/app/tests
